Separated the various parts of the robot so different commands can be send to each.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -813,6 +813,8 @@ TCL_LDFLAGS
 TCL_CPPFLAGS
 TCL_CONFIG_PATH
 HAS_TCL
+TCLSERV_LIBS
+TCLSERV_CFLAGS
 GENOM_LIBS
 GENOM_CFLAGS
 PKG_CONFIG
@@ -932,6 +934,8 @@ XENO_CONFIG
 PKG_CONFIG
 GENOM_CFLAGS
 GENOM_LIBS
+TCLSERV_CFLAGS
+TCLSERV_LIBS
 GENBASIC_CFLAGS
 GENBASIC_LIBS
 GENMANIP_CFLAGS
@@ -1605,6 +1609,10 @@ Some influential environment variables:
   GENOM_CFLAGS
               C compiler flags for GENOM, overriding pkg-config
   GENOM_LIBS  linker flags for GENOM, overriding pkg-config
+  TCLSERV_CFLAGS
+              C compiler flags for TCLSERV, overriding pkg-config
+  TCLSERV_LIBS
+              linker flags for TCLSERV, overriding pkg-config
   GENBASIC_CFLAGS
               C compiler flags for GENBASIC, overriding pkg-config
   GENBASIC_LIBS
@@ -4904,7 +4912,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4907 "configure"' > conftest.$ac_ext
+  echo '#line 4915 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7514,11 +7522,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7517: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7525: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7521: \$? = $ac_status" >&5
+   echo "$as_me:7529: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7804,11 +7812,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7807: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7815: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7811: \$? = $ac_status" >&5
+   echo "$as_me:7819: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7908,11 +7916,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7911: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7919: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7915: \$? = $ac_status" >&5
+   echo "$as_me:7923: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10310,7 +10318,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10313 "configure"
+#line 10321 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10410,7 +10418,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10413 "configure"
+#line 10421 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12823,11 +12831,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12826: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12834: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12830: \$? = $ac_status" >&5
+   echo "$as_me:12838: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12927,11 +12935,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12930: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12938: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12934: \$? = $ac_status" >&5
+   echo "$as_me:12942: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14512,11 +14520,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14515: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14523: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14519: \$? = $ac_status" >&5
+   echo "$as_me:14527: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14616,11 +14624,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14619: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14627: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14623: \$? = $ac_status" >&5
+   echo "$as_me:14631: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16837,11 +16845,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16840: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16848: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16844: \$? = $ac_status" >&5
+   echo "$as_me:16852: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17127,11 +17135,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17130: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17138: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17134: \$? = $ac_status" >&5
+   echo "$as_me:17142: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17231,11 +17239,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17234: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17242: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17238: \$? = $ac_status" >&5
+   echo "$as_me:17246: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21345,12 +21353,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GENOM_CFLAGS="$GENOM_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"genom >= 2.6\"") >&5
-  ($PKG_CONFIG --exists --print-errors "genom >= 2.6") 2>&5
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"genom >= 2.7\"") >&5
+  ($PKG_CONFIG --exists --print-errors "genom >= 2.7") 2>&5
   ac_status=$?
   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GENOM_CFLAGS=`$PKG_CONFIG --cflags "genom >= 2.6" 2>/dev/null`
+  pkg_cv_GENOM_CFLAGS=`$PKG_CONFIG --cflags "genom >= 2.7" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -21363,12 +21371,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GENOM_LIBS="$GENOM_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"genom >= 2.6\"") >&5
-  ($PKG_CONFIG --exists --print-errors "genom >= 2.6") 2>&5
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"genom >= 2.7\"") >&5
+  ($PKG_CONFIG --exists --print-errors "genom >= 2.7") 2>&5
   ac_status=$?
   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GENOM_LIBS=`$PKG_CONFIG --libs "genom >= 2.6" 2>/dev/null`
+  pkg_cv_GENOM_LIBS=`$PKG_CONFIG --libs "genom >= 2.7" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -21387,14 +21395,14 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GENOM_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "genom >= 2.6"`
+	        GENOM_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "genom >= 2.7"`
         else
-	        GENOM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "genom >= 2.6"`
+	        GENOM_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "genom >= 2.7"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GENOM_PKG_ERRORS" >&5
 
-	{ { $as_echo "$as_me:$LINENO: error: Package requirements (genom >= 2.6) were not met:
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (genom >= 2.7) were not met:
 
 $GENOM_PKG_ERRORS
 
@@ -21405,7 +21413,7 @@ Alternatively, you may set the environment variables GENOM_CFLAGS
 and GENOM_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 " >&5
-$as_echo "$as_me: error: Package requirements (genom >= 2.6) were not met:
+$as_echo "$as_me: error: Package requirements (genom >= 2.7) were not met:
 
 $GENOM_PKG_ERRORS
 
@@ -21451,6 +21459,119 @@ fi
 
 
 
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for TCLSERV" >&5
+$as_echo_n "checking for TCLSERV... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$TCLSERV_CFLAGS"; then
+        pkg_cv_TCLSERV_CFLAGS="$TCLSERV_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"tclserv >= 2.7\"") >&5
+  ($PKG_CONFIG --exists --print-errors "tclserv >= 2.7") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_TCLSERV_CFLAGS=`$PKG_CONFIG --cflags "tclserv >= 2.7" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$TCLSERV_LIBS"; then
+        pkg_cv_TCLSERV_LIBS="$TCLSERV_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"tclserv >= 2.7\"") >&5
+  ($PKG_CONFIG --exists --print-errors "tclserv >= 2.7") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_TCLSERV_LIBS=`$PKG_CONFIG --libs "tclserv >= 2.7" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        TCLSERV_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "tclserv >= 2.7"`
+        else
+	        TCLSERV_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "tclserv >= 2.7"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$TCLSERV_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (tclserv >= 2.7) were not met:
+
+$TCLSERV_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables TCLSERV_CFLAGS
+and TCLSERV_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (tclserv >= 2.7) were not met:
+
+$TCLSERV_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables TCLSERV_CFLAGS
+and TCLSERV_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables TCLSERV_CFLAGS
+and TCLSERV_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables TCLSERV_CFLAGS
+and TCLSERV_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	TCLSERV_CFLAGS=$pkg_cv_TCLSERV_CFLAGS
+	TCLSERV_LIBS=$pkg_cv_TCLSERV_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
 
    case $host_cpu-$host_os in
       x86_64-linux*)
